// Generated by gencpp from file robot_tutorials/maxTwoIntsRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_TUTORIALS_MESSAGE_MAXTWOINTSREQUEST_H
#define ROBOT_TUTORIALS_MESSAGE_MAXTWOINTSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_tutorials
{
template <class ContainerAllocator>
struct maxTwoIntsRequest_
{
  typedef maxTwoIntsRequest_<ContainerAllocator> Type;

  maxTwoIntsRequest_()
    : a(0)
    , b(0)  {
    }
  maxTwoIntsRequest_(const ContainerAllocator& _alloc)
    : a(0)
    , b(0)  {
  (void)_alloc;
    }



   typedef int64_t _a_type;
  _a_type a;

   typedef int64_t _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::robot_tutorials::maxTwoIntsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_tutorials::maxTwoIntsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct maxTwoIntsRequest_

typedef ::robot_tutorials::maxTwoIntsRequest_<std::allocator<void> > maxTwoIntsRequest;

typedef boost::shared_ptr< ::robot_tutorials::maxTwoIntsRequest > maxTwoIntsRequestPtr;
typedef boost::shared_ptr< ::robot_tutorials::maxTwoIntsRequest const> maxTwoIntsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_tutorials::maxTwoIntsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_tutorials::maxTwoIntsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_tutorials::maxTwoIntsRequest_<ContainerAllocator1> & lhs, const ::robot_tutorials::maxTwoIntsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.b == rhs.b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_tutorials::maxTwoIntsRequest_<ContainerAllocator1> & lhs, const ::robot_tutorials::maxTwoIntsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_tutorials::maxTwoIntsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_tutorials::maxTwoIntsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_tutorials::maxTwoIntsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_tutorials::maxTwoIntsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_tutorials::maxTwoIntsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_tutorials::maxTwoIntsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_tutorials::maxTwoIntsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "36d09b846be0b371c5f190354dd3153e";
  }

  static const char* value(const ::robot_tutorials::maxTwoIntsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x36d09b846be0b371ULL;
  static const uint64_t static_value2 = 0xc5f190354dd3153eULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_tutorials::maxTwoIntsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_tutorials/maxTwoIntsRequest";
  }

  static const char* value(const ::robot_tutorials::maxTwoIntsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_tutorials::maxTwoIntsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 a\n"
"int64 b\n"
;
  }

  static const char* value(const ::robot_tutorials::maxTwoIntsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_tutorials::maxTwoIntsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct maxTwoIntsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_tutorials::maxTwoIntsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_tutorials::maxTwoIntsRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int64_t>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<int64_t>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_TUTORIALS_MESSAGE_MAXTWOINTSREQUEST_H
